"""add parametric_backtest_metrics to strategies

Revision ID: a066baad48f7
Revises: ea871ba50cf7
Create Date: 2026-01-04 22:32:23.609911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a066baad48f7'
down_revision: Union[str, Sequence[str], None] = 'ea871ba50cf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('parametric_backtest_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategies', 'parametric_backtest_metrics')
    # ### end Alembic commands ###
