"""add credentials table

Revision ID: b4312de95e92
Revises: 5b467cdc97da
Create Date: 2026-01-08 12:44:52.056255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4312de95e92'
down_revision: Union[str, Sequence[str], None] = '5b467cdc97da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credentials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('credential_type', sa.String(length=20), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_address', sa.String(length=42), nullable=False),
    sa.Column('subaccount_id', sa.Integer(), nullable=True),
    sa.Column('subaccount_name', sa.String(length=100), nullable=True),
    sa.Column('agent_name', sa.String(length=100), nullable=True),
    sa.Column('agent_address', sa.String(length=42), nullable=False),
    sa.Column('private_key', sa.String(length=66), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_credential_active_subaccount', 'credentials', ['is_active', 'subaccount_id'], unique=False)
    op.create_index('idx_credential_expiry', 'credentials', ['expires_at', 'is_active'], unique=False)
    op.create_index('idx_credential_target', 'credentials', ['target_type', 'target_address'], unique=False)
    op.create_index(op.f('ix_credentials_is_active'), 'credentials', ['is_active'], unique=False)
    op.create_index(op.f('ix_credentials_subaccount_id'), 'credentials', ['subaccount_id'], unique=False)
    op.create_index(op.f('ix_credentials_target_type'), 'credentials', ['target_type'], unique=False)
    op.drop_constraint(op.f('backtest_results_recent_result_id_fkey'), 'backtest_results', type_='foreignkey')
    op.create_foreign_key(None, 'backtest_results', 'backtest_results', ['recent_result_id'], ['id'])
    op.alter_column('pipeline_metrics_snapshots', 'queue_active',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pipeline_metrics_snapshots', 'queue_tested',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pipeline_metrics_snapshots', 'queue_selected',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('idx_last_backtested'), table_name='strategies')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_last_backtested'), 'strategies', ['last_backtested_at'], unique=False)
    op.alter_column('pipeline_metrics_snapshots', 'queue_selected',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pipeline_metrics_snapshots', 'queue_tested',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pipeline_metrics_snapshots', 'queue_active',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'backtest_results', type_='foreignkey')
    op.create_foreign_key(op.f('backtest_results_recent_result_id_fkey'), 'backtest_results', 'backtest_results', ['recent_result_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_credentials_target_type'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_subaccount_id'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_is_active'), table_name='credentials')
    op.drop_index('idx_credential_target', table_name='credentials')
    op.drop_index('idx_credential_expiry', table_name='credentials')
    op.drop_index('idx_credential_active_subaccount', table_name='credentials')
    op.drop_table('credentials')
    # ### end Alembic commands ###
