"""add pipeline metrics snapshots table

Revision ID: ea871ba50cf7
Revises: 013_add_weighted_metrics
Create Date: 2026-01-04 19:38:44.566680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea871ba50cf7'
down_revision: Union[str, Sequence[str], None] = '013_add_weighted_metrics'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_metrics_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('queue_generated', sa.Integer(), nullable=False),
    sa.Column('queue_validated', sa.Integer(), nullable=False),
    sa.Column('queue_tested', sa.Integer(), nullable=False),
    sa.Column('queue_selected', sa.Integer(), nullable=False),
    sa.Column('queue_live', sa.Integer(), nullable=False),
    sa.Column('queue_retired', sa.Integer(), nullable=False),
    sa.Column('queue_failed', sa.Integer(), nullable=False),
    sa.Column('throughput_generation', sa.Float(), nullable=True),
    sa.Column('throughput_validation', sa.Float(), nullable=True),
    sa.Column('throughput_backtesting', sa.Float(), nullable=True),
    sa.Column('throughput_classification', sa.Float(), nullable=True),
    sa.Column('utilization_generated', sa.Float(), nullable=True),
    sa.Column('utilization_validated', sa.Float(), nullable=True),
    sa.Column('utilization_tested', sa.Float(), nullable=True),
    sa.Column('success_rate_validation', sa.Float(), nullable=True),
    sa.Column('success_rate_backtesting', sa.Float(), nullable=True),
    sa.Column('bottleneck_stage', sa.String(length=50), nullable=True),
    sa.Column('overall_status', sa.String(length=20), nullable=False),
    sa.Column('avg_sharpe', sa.Float(), nullable=True),
    sa.Column('avg_win_rate', sa.Float(), nullable=True),
    sa.Column('avg_expectancy', sa.Float(), nullable=True),
    sa.Column('pattern_count', sa.Integer(), nullable=False),
    sa.Column('ai_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_metrics_status_time', 'pipeline_metrics_snapshots', ['overall_status', 'timestamp'], unique=False)
    op.create_index('idx_metrics_timestamp', 'pipeline_metrics_snapshots', ['timestamp'], unique=False)
    op.create_index(op.f('ix_pipeline_metrics_snapshots_timestamp'), 'pipeline_metrics_snapshots', ['timestamp'], unique=False)
    op.alter_column('backtest_results', 'weighted_sharpe_pure',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Sharpe ratio weighted: training*0.4 + holdout*0.6',
               existing_nullable=True)
    op.alter_column('backtest_results', 'weighted_walk_forward_stability',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Walk-forward stability weighted: training*0.4 + holdout*0.6',
               existing_nullable=True)
    op.drop_constraint(op.f('fk_backtest_results_recent_result'), 'backtest_results', type_='foreignkey')
    op.create_foreign_key(None, 'backtest_results', 'backtest_results', ['recent_result_id'], ['id'])
    op.drop_index(op.f('idx_coins_is_active'), table_name='coins')
    op.create_index(op.f('ix_coins_is_active'), 'coins', ['is_active'], unique=False)
    op.drop_index(op.f('idx_backtest_completed'), table_name='strategies')
    op.drop_index(op.f('idx_strategies_score_backtest'), table_name='strategies', postgresql_where="(status = ANY (ARRAY['TESTED'::strategy_status, 'SELECTED'::strategy_status]))")
    op.drop_index(op.f('idx_strategies_score_live'), table_name='strategies', postgresql_where="(status = 'LIVE'::strategy_status)")
    op.drop_index(op.f('idx_strategies_template_id'), table_name='strategies')
    op.drop_index(op.f('idx_validation_completed'), table_name='strategies')
    op.create_index(op.f('ix_strategies_template_id'), 'strategies', ['template_id'], unique=False)
    op.alter_column('strategy_templates', 'strategies_generated',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('strategy_templates', 'strategies_profitable',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('idx_template_structure_id'), table_name='strategy_templates')
    op.drop_index(op.f('idx_template_structure_type'), table_name='strategy_templates')
    op.create_index(op.f('ix_strategy_templates_structure_id'), 'strategy_templates', ['structure_id'], unique=False)
    op.drop_index(op.f('idx_trades_position_id'), table_name='trades')
    op.create_index(op.f('ix_trades_position_id'), 'trades', ['position_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_position_id'), table_name='trades')
    op.create_index(op.f('idx_trades_position_id'), 'trades', ['position_id'], unique=False)
    op.drop_index(op.f('ix_strategy_templates_structure_id'), table_name='strategy_templates')
    op.create_index(op.f('idx_template_structure_type'), 'strategy_templates', ['structure_id', 'strategy_type'], unique=False)
    op.create_index(op.f('idx_template_structure_id'), 'strategy_templates', ['structure_id'], unique=False)
    op.alter_column('strategy_templates', 'strategies_profitable',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('strategy_templates', 'strategies_generated',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_strategies_template_id'), table_name='strategies')
    op.create_index(op.f('idx_validation_completed'), 'strategies', ['validation_completed_at'], unique=False)
    op.create_index(op.f('idx_strategies_template_id'), 'strategies', ['template_id'], unique=False)
    op.create_index(op.f('idx_strategies_score_live'), 'strategies', ['score_live'], unique=False, postgresql_where="(status = 'LIVE'::strategy_status)")
    op.create_index(op.f('idx_strategies_score_backtest'), 'strategies', ['score_backtest'], unique=False, postgresql_where="(status = ANY (ARRAY['TESTED'::strategy_status, 'SELECTED'::strategy_status]))")
    op.create_index(op.f('idx_backtest_completed'), 'strategies', ['backtest_completed_at'], unique=False)
    op.drop_index(op.f('ix_coins_is_active'), table_name='coins')
    op.create_index(op.f('idx_coins_is_active'), 'coins', ['is_active'], unique=False)
    op.drop_constraint(None, 'backtest_results', type_='foreignkey')
    op.create_foreign_key(op.f('fk_backtest_results_recent_result'), 'backtest_results', 'backtest_results', ['recent_result_id'], ['id'], ondelete='SET NULL')
    op.alter_column('backtest_results', 'weighted_walk_forward_stability',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Walk-forward stability weighted: training*0.4 + holdout*0.6',
               existing_nullable=True)
    op.alter_column('backtest_results', 'weighted_sharpe_pure',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Sharpe ratio weighted: training*0.4 + holdout*0.6',
               existing_nullable=True)
    op.drop_index(op.f('ix_pipeline_metrics_snapshots_timestamp'), table_name='pipeline_metrics_snapshots')
    op.drop_index('idx_metrics_timestamp', table_name='pipeline_metrics_snapshots')
    op.drop_index('idx_metrics_status_time', table_name='pipeline_metrics_snapshots')
    op.drop_table('pipeline_metrics_snapshots')
    # ### end Alembic commands ###
