"""
Pandas-TA Indicator Registry

Contains 80+ indicators from pandas_ta organized by category.
Each indicator has:
- Standard parameter values (trading-sensible)
- Category for regime mapping
- Direction compatibility
- Output column patterns
"""

from dataclasses import dataclass, field
from typing import Literal


@dataclass
class PtaIndicator:
    """Single pandas_ta indicator definition."""

    id: str                                    # Unique ID: "RSI", "EMA", "SUPERTREND"
    name: str                                  # Human-readable: "Relative Strength Index"
    category: str                              # "momentum", "trend", "volatility", "volume"
    pandas_ta_func: str                        # Function name in pandas_ta: "rsi", "ema"
    params: dict[str, list]                    # {"length": [7, 14, 21, 28]}
    output_columns: list[str]                  # Column name patterns
    regime_type: Literal["TREND", "REVERSAL", "BOTH"]
    direction: Literal["LONG", "SHORT", "BIDI"]
    lookback: int = 50                         # Minimum bars required
    input_type: str = "close"                  # "close", "hlc", "hlcv", "ohlcv"


# =============================================================================
# MOMENTUM INDICATORS (Mean Reversion - REVERSAL regime)
# =============================================================================

MOMENTUM_INDICATORS = [
    PtaIndicator(
        id="RSI",
        name="Relative Strength Index",
        category="momentum",
        pandas_ta_func="rsi",
        params={"length": [7, 14, 21, 28]},
        output_columns=["RSI_{length}"],
        regime_type="REVERSAL",
        direction="BIDI",
        lookback=30,
        input_type="close",
    ),
    PtaIndicator(
        id="STOCH_K",
        name="Stochastic %K",
        category="momentum",
        pandas_ta_func="stoch",
        params={"k": [5, 14], "d": [3, 5], "smooth_k": [3, 5]},
        output_columns=["STOCHk_{k}_{d}_{smooth_k}", "STOCHd_{k}_{d}_{smooth_k}"],
        regime_type="REVERSAL",
        direction="BIDI",
        lookback=30,
        input_type="hlc",
    ),
    PtaIndicator(
        id="CCI",
        name="Commodity Channel Index",
        category="momentum",
        pandas_ta_func="cci",
        params={"length": [14, 20, 28]},
        output_columns=["CCI_{length}_0.015"],
        regime_type="REVERSAL",
        direction="BIDI",
        lookback=30,
        input_type="hlc",
    ),
    PtaIndicator(
        id="WILLR",
        name="Williams %R",
        category="momentum",
        pandas_ta_func="willr",
        params={"length": [14, 21, 28]},
        output_columns=["WILLR_{length}"],
        regime_type="REVERSAL",
        direction="BIDI",
        lookback=30,
        input_type="hlc",
    ),
    PtaIndicator(
        id="CMO",
        name="Chande Momentum Oscillator",
        category="momentum",
        pandas_ta_func="cmo",
        params={"length": [9, 14, 21]},
        output_columns=["CMO_{length}"],
        regime_type="REVERSAL",
        direction="BIDI",
        lookback=30,
        input_type="close",
    ),
    PtaIndicator(
        id="ROC",
        name="Rate of Change",
        category="momentum",
        pandas_ta_func="roc",
        params={"length": [9, 12, 21]},
        output_columns=["ROC_{length}"],
        regime_type="REVERSAL",
        direction="BIDI",
        lookback=30,
        input_type="close",
    ),
    PtaIndicator(
        id="MOM",
        name="Momentum",
        category="momentum",
        pandas_ta_func="mom",
        params={"length": [10, 14, 21]},
        output_columns=["MOM_{length}"],
        regime_type="REVERSAL",
        direction="BIDI",
        lookback=30,
        input_type="close",
    ),
    PtaIndicator(
        id="TSI",
        name="True Strength Index",
        category="momentum",
        pandas_ta_func="tsi",
        params={"fast": [10, 13, 18], "slow": [20, 25, 30]},
        output_columns=["TSI_{fast}_{slow}", "TSIs_{fast}_{slow}"],
        regime_type="REVERSAL",
        direction="BIDI",
        lookback=40,
        input_type="close",
    ),
    PtaIndicator(
        id="UO",
        name="Ultimate Oscillator",
        category="momentum",
        pandas_ta_func="uo",
        params={"fast": [5, 7, 10], "medium": [10, 14, 21], "slow": [21, 28, 35]},
        output_columns=["UO_{fast}_{medium}_{slow}"],
        regime_type="REVERSAL",
        direction="BIDI",
        lookback=40,
        input_type="hlc",
    ),
    PtaIndicator(
        id="AO",
        name="Awesome Oscillator",
        category="momentum",
        pandas_ta_func="ao",
        params={"fast": [3, 5, 8], "slow": [25, 34, 45]},
        output_columns=["AO_{fast}_{slow}"],
        regime_type="REVERSAL",
        direction="BIDI",
        lookback=50,
        input_type="hl",
    ),
    PtaIndicator(
        id="MFI",
        name="Money Flow Index",
        category="momentum",
        pandas_ta_func="mfi",
        params={"length": [14, 21]},
        output_columns=["MFI_{length}"],
        regime_type="REVERSAL",
        direction="BIDI",
        lookback=30,
        input_type="hlcv",
    ),
    # =========================================================================
    # NEW MOMENTUM INDICATORS (Expanded exploration)
    # =========================================================================
    PtaIndicator(
        id="APO",
        name="Absolute Price Oscillator",
        category="momentum",
        pandas_ta_func="apo",
        params={"fast": [8, 12, 16], "slow": [21, 26, 32]},
        output_columns=["APO_{fast}_{slow}"],
        regime_type="REVERSAL",
        direction="BIDI",
        lookback=40,
        input_type="close",
    ),
    PtaIndicator(
        id="BIAS",
        name="Bias",
        category="momentum",
        pandas_ta_func="bias",
        params={"length": [14, 20, 26]},
        output_columns=["BIAS_{length}"],
        regime_type="REVERSAL",
        direction="BIDI",
        lookback=30,
        input_type="close",
    ),
    PtaIndicator(
        id="BOP",
        name="Balance of Power",
        category="momentum",
        pandas_ta_func="bop",
        params={},
        output_columns=["BOP"],
        regime_type="REVERSAL",
        direction="BIDI",
        lookback=10,
        input_type="ohlc",
    ),
    PtaIndicator(
        id="BRAR",
        name="BRAR (BR and AR)",
        category="momentum",
        pandas_ta_func="brar",
        params={"length": [20, 26, 30]},
        output_columns=["AR_{length}", "BR_{length}"],
        regime_type="REVERSAL",
        direction="BIDI",
        lookback=40,
        input_type="ohlc",
    ),
    PtaIndicator(
        id="CFO",
        name="Chande Forecast Oscillator",
        category="momentum",
        pandas_ta_func="cfo",
        params={"length": [9, 14, 21]},
        output_columns=["CFO_{length}"],
        regime_type="REVERSAL",
        direction="BIDI",
        lookback=30,
        input_type="close",
    ),
    PtaIndicator(
        id="CG",
        name="Center of Gravity",
        category="momentum",
        pandas_ta_func="cg",
        params={"length": [10, 14, 20]},
        output_columns=["CG_{length}"],
        regime_type="REVERSAL",
        direction="BIDI",
        lookback=30,
        input_type="close",
    ),
    PtaIndicator(
        id="COPPOCK",
        name="Coppock Curve",
        category="momentum",
        pandas_ta_func="coppock",
        params={"length": [10, 14], "fast": [11, 14], "slow": [14, 21]},
        output_columns=["COPC_{length}_{fast}_{slow}"],
        regime_type="REVERSAL",
        direction="BIDI",
        lookback=40,
        input_type="close",
    ),
    PtaIndicator(
        id="CTI",
        name="Correlation Trend Indicator",
        category="momentum",
        pandas_ta_func="cti",
        params={"length": [12, 20, 30]},
        output_columns=["CTI_{length}"],
        regime_type="REVERSAL",
        direction="BIDI",
        lookback=35,
        input_type="close",
    ),
    PtaIndicator(
        id="ER",
        name="Efficiency Ratio",
        category="momentum",
        pandas_ta_func="er",
        params={"length": [10, 14, 21]},
        output_columns=["ER_{length}"],
        regime_type="REVERSAL",
        direction="BIDI",
        lookback=30,
        input_type="close",
    ),
    PtaIndicator(
        id="FISHER",
        name="Fisher Transform",
        category="momentum",
        pandas_ta_func="fisher",
        params={"length": [9, 14, 21]},
        output_columns=["FISHERT_{length}", "FISHERTs_{length}"],
        regime_type="REVERSAL",
        direction="BIDI",
        lookback=30,
        input_type="hl",
    ),
    PtaIndicator(
        id="INERTIA",
        name="Inertia",
        category="momentum",
        pandas_ta_func="inertia",
        params={"length": [14, 20, 28]},
        output_columns=["INERTIA_{length}"],
        regime_type="REVERSAL",
        direction="BIDI",
        lookback=35,
        input_type="close",
    ),
    PtaIndicator(
        id="KDJ",
        name="KDJ",
        category="momentum",
        pandas_ta_func="kdj",
        params={"length": [9, 14, 21]},
        output_columns=["K_{length}", "D_{length}", "J_{length}"],
        regime_type="REVERSAL",
        direction="BIDI",
        lookback=30,
        input_type="hlc",
    ),
    PtaIndicator(
        id="KST",
        name="Know Sure Thing",
        category="momentum",
        pandas_ta_func="kst",
        params={"roc1": [10], "roc2": [15], "roc3": [20], "roc4": [30]},
        output_columns=["KST_{roc1}_{roc2}_{roc3}_{roc4}", "KSTs_{roc1}_{roc2}_{roc3}_{roc4}"],
        regime_type="REVERSAL",
        direction="BIDI",
        lookback=50,
        input_type="close",
    ),
    PtaIndicator(
        id="PGO",
        name="Pretty Good Oscillator",
        category="momentum",
        pandas_ta_func="pgo",
        params={"length": [14, 21, 28]},
        output_columns=["PGO_{length}"],
        regime_type="REVERSAL",
        direction="BIDI",
        lookback=35,
        input_type="hlc",
    ),
    PtaIndicator(
        id="PSL",
        name="Psychological Line",
        category="momentum",
        pandas_ta_func="psl",
        params={"length": [12, 20, 28]},
        output_columns=["PSL_{length}"],
        regime_type="REVERSAL",
        direction="BIDI",
        lookback=35,
        input_type="close",
    ),
    PtaIndicator(
        id="QQE",
        name="Quantitative Qualitative Estimation",
        category="momentum",
        pandas_ta_func="qqe",
        params={"length": [14, 21], "smooth": [5, 7]},
        output_columns=["QQE_{length}_{smooth}"],
        regime_type="REVERSAL",
        direction="BIDI",
        lookback=40,
        input_type="close",
    ),
    PtaIndicator(
        id="RSX",
        name="Relative Strength Xtra",
        category="momentum",
        pandas_ta_func="rsx",
        params={"length": [14, 21, 28]},
        output_columns=["RSX_{length}"],
        regime_type="REVERSAL",
        direction="BIDI",
        lookback=35,
        input_type="close",
    ),
    PtaIndicator(
        id="RVGI",
        name="Relative Vigor Index",
        category="momentum",
        pandas_ta_func="rvgi",
        params={"length": [10, 14, 21]},
        output_columns=["RVGI_{length}", "RVGIs_{length}"],
        regime_type="REVERSAL",
        direction="BIDI",
        lookback=30,
        input_type="ohlc",
    ),
    PtaIndicator(
        id="SLOPE",
        name="Slope",
        category="momentum",
        pandas_ta_func="slope",
        params={"length": [14, 20, 28]},
        output_columns=["SLOPE_{length}"],
        regime_type="REVERSAL",
        direction="BIDI",
        lookback=35,
        input_type="close",
    ),
    PtaIndicator(
        id="SMI",
        name="Stochastic Momentum Index",
        category="momentum",
        pandas_ta_func="smi",
        params={"fast": [5, 8], "slow": [20, 25], "signal": [5, 9]},
        output_columns=["SMI_{fast}_{slow}_{signal}", "SMIs_{fast}_{slow}_{signal}"],
        regime_type="REVERSAL",
        direction="BIDI",
        lookback=40,
        input_type="hlc",
    ),
    PtaIndicator(
        id="SQUEEZE",
        name="Squeeze Momentum",
        category="momentum",
        pandas_ta_func="squeeze",
        params={"bb_length": [20], "bb_std": [2.0], "kc_length": [20], "kc_scalar": [1.5, 2.0]},
        output_columns=["SQZ_{bb_length}_{bb_std}_{kc_length}_{kc_scalar}"],
        regime_type="REVERSAL",
        direction="BIDI",
        lookback=30,
        input_type="hlc",
    ),
    PtaIndicator(
        id="SQUEEZE_PRO",
        name="Squeeze Pro",
        category="momentum",
        pandas_ta_func="squeeze_pro",
        params={"bb_length": [20], "bb_std": [2.0], "kc_length": [20], "kc_scalar": [1.5, 2.0]},
        output_columns=["SQZPRO_{bb_length}_{bb_std}_{kc_length}_{kc_scalar}"],
        regime_type="REVERSAL",
        direction="BIDI",
        lookback=30,
        input_type="hlc",
    ),
    PtaIndicator(
        id="STC",
        name="Schaff Trend Cycle",
        category="momentum",
        pandas_ta_func="stc",
        params={"tclength": [10, 14], "fast": [23, 26], "slow": [50, 55]},
        output_columns=["STC_{tclength}_{fast}_{slow}"],
        regime_type="REVERSAL",
        direction="BIDI",
        lookback=60,
        input_type="close",
    ),
    PtaIndicator(
        id="STOCHRSI",
        name="Stochastic RSI",
        category="momentum",
        pandas_ta_func="stochrsi",
        params={"length": [14, 21], "rsi_length": [14, 21]},
        output_columns=["STOCHRSIk_{length}_{rsi_length}", "STOCHRSId_{length}_{rsi_length}"],
        regime_type="REVERSAL",
        direction="BIDI",
        lookback=40,
        input_type="close",
    ),
    PtaIndicator(
        id="TMO",
        name="True Momentum Oscillator",
        category="momentum",
        pandas_ta_func="tmo",
        params={"length": [14, 21], "smooth": [5, 7]},
        output_columns=["TMO_{length}_{smooth}", "TMOs_{length}_{smooth}"],
        regime_type="REVERSAL",
        direction="BIDI",
        lookback=40,
        input_type="ohlc",
    ),
]


# =============================================================================
# TREND INDICATORS (Trend Following - TREND regime)
# =============================================================================

TREND_INDICATORS = [
    PtaIndicator(
        id="EMA",
        name="Exponential Moving Average",
        category="trend",
        pandas_ta_func="ema",
        params={"length": [8, 12, 20, 26, 50, 100, 200]},
        output_columns=["EMA_{length}"],
        regime_type="TREND",
        direction="BIDI",
        lookback=200,
        input_type="close",
    ),
    PtaIndicator(
        id="SMA",
        name="Simple Moving Average",
        category="trend",
        pandas_ta_func="sma",
        params={"length": [10, 20, 50, 100, 200]},
        output_columns=["SMA_{length}"],
        regime_type="TREND",
        direction="BIDI",
        lookback=200,
        input_type="close",
    ),
    PtaIndicator(
        id="SUPERTREND",
        name="Supertrend",
        category="trend",
        pandas_ta_func="supertrend",
        params={"length": [7, 10, 14], "multiplier": [2.0, 3.0, 4.0]},
        output_columns=["SUPERT_{length}_{multiplier}", "SUPERTd_{length}_{multiplier}"],
        regime_type="TREND",
        direction="BIDI",
        lookback=30,
        input_type="hlc",
    ),
    PtaIndicator(
        id="PSAR",
        name="Parabolic SAR",
        category="trend",
        pandas_ta_func="psar",
        params={"af0": [0.01, 0.02, 0.03], "max_af": [0.1, 0.2, 0.3]},
        output_columns=["PSARl_{af0}_{max_af}", "PSARs_{af0}_{max_af}"],
        regime_type="TREND",
        direction="BIDI",
        lookback=30,
        input_type="hlc",
    ),
    PtaIndicator(
        id="HMA",
        name="Hull Moving Average",
        category="trend",
        pandas_ta_func="hma",
        params={"length": [9, 14, 21, 50]},
        output_columns=["HMA_{length}"],
        regime_type="TREND",
        direction="BIDI",
        lookback=60,
        input_type="close",
    ),
    PtaIndicator(
        id="DEMA",
        name="Double EMA",
        category="trend",
        pandas_ta_func="dema",
        params={"length": [10, 20, 50]},
        output_columns=["DEMA_{length}"],
        regime_type="TREND",
        direction="BIDI",
        lookback=60,
        input_type="close",
    ),
    PtaIndicator(
        id="TEMA",
        name="Triple EMA",
        category="trend",
        pandas_ta_func="tema",
        params={"length": [10, 20, 50]},
        output_columns=["TEMA_{length}"],
        regime_type="TREND",
        direction="BIDI",
        lookback=80,
        input_type="close",
    ),
    PtaIndicator(
        id="T3",
        name="T3 Moving Average",
        category="trend",
        pandas_ta_func="t3",
        params={"length": [5, 10, 20]},
        output_columns=["T3_{length}"],
        regime_type="TREND",
        direction="BIDI",
        lookback=60,
        input_type="close",
    ),
    PtaIndicator(
        id="KAMA",
        name="Kaufman Adaptive MA",
        category="trend",
        pandas_ta_func="kama",
        params={"length": [10, 14, 21], "fast": [2, 3], "slow": [20, 30]},
        output_columns=["KAMA_{length}_{fast}_{slow}"],
        regime_type="TREND",
        direction="BIDI",
        lookback=50,
        input_type="close",
    ),
    PtaIndicator(
        id="ZLMA",
        name="Zero Lag MA",
        category="trend",
        pandas_ta_func="zlma",
        params={"length": [10, 20, 50]},
        output_columns=["ZL_EMA_{length}"],
        regime_type="TREND",
        direction="BIDI",
        lookback=60,
        input_type="close",
    ),
    # =========================================================================
    # NEW OVERLAP/TREND INDICATORS (Expanded exploration)
    # =========================================================================
    PtaIndicator(
        id="ALMA",
        name="Arnaud Legoux Moving Average",
        category="trend",
        pandas_ta_func="alma",
        params={"length": [9, 14, 20, 30], "offset": [0.85], "sigma": [6]},
        output_columns=["ALMA_{length}_{offset}_{sigma}"],
        regime_type="TREND",
        direction="BIDI",
        lookback=40,
        input_type="close",
    ),
    PtaIndicator(
        id="FWMA",
        name="Fibonacci Weighted MA",
        category="trend",
        pandas_ta_func="fwma",
        params={"length": [10, 14, 20, 30]},
        output_columns=["FWMA_{length}"],
        regime_type="TREND",
        direction="BIDI",
        lookback=40,
        input_type="close",
    ),
    PtaIndicator(
        id="HILO",
        name="Gann High-Low Activator",
        category="trend",
        pandas_ta_func="hilo",
        params={"high_length": [13, 20], "low_length": [21, 28]},
        output_columns=["HILO_{high_length}_{low_length}"],
        regime_type="TREND",
        direction="BIDI",
        lookback=40,
        input_type="hlc",
    ),
    PtaIndicator(
        id="HWMA",
        name="Holt-Winter Moving Average",
        category="trend",
        pandas_ta_func="hwma",
        params={"na": [0.2], "nb": [0.1], "nc": [0.1]},
        output_columns=["HWMA"],
        regime_type="TREND",
        direction="BIDI",
        lookback=30,
        input_type="close",
    ),
    PtaIndicator(
        id="LINREG",
        name="Linear Regression",
        category="trend",
        pandas_ta_func="linreg",
        params={"length": [14, 20, 28]},
        output_columns=["LINREG_{length}"],
        regime_type="TREND",
        direction="BIDI",
        lookback=35,
        input_type="close",
    ),
    PtaIndicator(
        id="MCGD",
        name="McGinley Dynamic",
        category="trend",
        pandas_ta_func="mcgd",
        params={"length": [10, 14, 21]},
        output_columns=["MCGD_{length}"],
        regime_type="TREND",
        direction="BIDI",
        lookback=30,
        input_type="close",
    ),
    PtaIndicator(
        id="MIDPOINT",
        name="Midpoint",
        category="trend",
        pandas_ta_func="midpoint",
        params={"length": [14, 20, 28]},
        output_columns=["MIDPOINT_{length}"],
        regime_type="TREND",
        direction="BIDI",
        lookback=35,
        input_type="close",
    ),
    PtaIndicator(
        id="MIDPRICE",
        name="Midprice",
        category="trend",
        pandas_ta_func="midprice",
        params={"length": [14, 20, 28]},
        output_columns=["MIDPRICE_{length}"],
        regime_type="TREND",
        direction="BIDI",
        lookback=35,
        input_type="hl",
    ),
    PtaIndicator(
        id="PWMA",
        name="Pascal's Weighted MA",
        category="trend",
        pandas_ta_func="pwma",
        params={"length": [10, 14, 20, 30]},
        output_columns=["PWMA_{length}"],
        regime_type="TREND",
        direction="BIDI",
        lookback=40,
        input_type="close",
    ),
    PtaIndicator(
        id="RMA",
        name="Wilders Moving Average",
        category="trend",
        pandas_ta_func="rma",
        params={"length": [14, 21, 28]},
        output_columns=["RMA_{length}"],
        regime_type="TREND",
        direction="BIDI",
        lookback=35,
        input_type="close",
    ),
    PtaIndicator(
        id="SINWMA",
        name="Sine Weighted MA",
        category="trend",
        pandas_ta_func="sinwma",
        params={"length": [14, 21, 28]},
        output_columns=["SINWMA_{length}"],
        regime_type="TREND",
        direction="BIDI",
        lookback=35,
        input_type="close",
    ),
    PtaIndicator(
        id="SSF",
        name="Ehlers Super Smoother Filter",
        category="trend",
        pandas_ta_func="ssf",
        params={"length": [10, 14, 20]},
        output_columns=["SSF_{length}"],
        regime_type="TREND",
        direction="BIDI",
        lookback=30,
        input_type="close",
    ),
    PtaIndicator(
        id="SWMA",
        name="Symmetric Weighted MA",
        category="trend",
        pandas_ta_func="swma",
        params={"length": [10, 14, 20]},
        output_columns=["SWMA_{length}"],
        regime_type="TREND",
        direction="BIDI",
        lookback=30,
        input_type="close",
    ),
    PtaIndicator(
        id="TRIMA",
        name="Triangular Moving Average",
        category="trend",
        pandas_ta_func="trima",
        params={"length": [14, 21, 30]},
        output_columns=["TRIMA_{length}"],
        regime_type="TREND",
        direction="BIDI",
        lookback=40,
        input_type="close",
    ),
    PtaIndicator(
        id="VIDYA",
        name="Variable Index Dynamic Average",
        category="trend",
        pandas_ta_func="vidya",
        params={"length": [14, 21, 28]},
        output_columns=["VIDYA_{length}"],
        regime_type="TREND",
        direction="BIDI",
        lookback=35,
        input_type="close",
    ),
    PtaIndicator(
        id="WMA",
        name="Weighted Moving Average",
        category="trend",
        pandas_ta_func="wma",
        params={"length": [10, 14, 21, 50]},
        output_columns=["WMA_{length}"],
        regime_type="TREND",
        direction="BIDI",
        lookback=60,
        input_type="close",
    ),
    PtaIndicator(
        id="WCP",
        name="Weighted Close Price",
        category="trend",
        pandas_ta_func="wcp",
        params={},
        output_columns=["WCP"],
        regime_type="TREND",
        direction="BIDI",
        lookback=10,
        input_type="hlc",
    ),
]


# =============================================================================
# CROSSOVER INDICATORS (Trend Following - TREND regime)
# =============================================================================

CROSSOVER_INDICATORS = [
    PtaIndicator(
        id="MACD",
        name="MACD",
        category="crossover",
        pandas_ta_func="macd",
        params={"fast": [8, 12], "slow": [21, 26], "signal": [7, 9]},
        output_columns=["MACD_{fast}_{slow}_{signal}", "MACDh_{fast}_{slow}_{signal}", "MACDs_{fast}_{slow}_{signal}"],
        regime_type="TREND",
        direction="BIDI",
        lookback=40,
        input_type="close",
    ),
    PtaIndicator(
        id="PPO",
        name="Percentage Price Oscillator",
        category="crossover",
        pandas_ta_func="ppo",
        params={"fast": [8, 12, 16], "slow": [20, 26, 32], "signal": [7, 9, 12]},
        output_columns=["PPO_{fast}_{slow}_{signal}", "PPOh_{fast}_{slow}_{signal}", "PPOs_{fast}_{slow}_{signal}"],
        regime_type="TREND",
        direction="BIDI",
        lookback=40,
        input_type="close",
    ),
    PtaIndicator(
        id="TRIX",
        name="TRIX",
        category="crossover",
        pandas_ta_func="trix",
        params={"length": [14, 18, 30]},
        output_columns=["TRIX_{length}", "TRIXs_{length}"],
        regime_type="TREND",
        direction="BIDI",
        lookback=50,
        input_type="close",
    ),
    PtaIndicator(
        id="ADX",
        name="Average Directional Index",
        category="crossover",
        pandas_ta_func="adx",
        params={"length": [14, 20, 25]},
        output_columns=["ADX_{length}", "DMP_{length}", "DMN_{length}"],
        regime_type="TREND",
        direction="BIDI",
        lookback=40,
        input_type="hlc",
    ),
    PtaIndicator(
        id="AROON",
        name="Aroon",
        category="crossover",
        pandas_ta_func="aroon",
        params={"length": [14, 25]},
        output_columns=["AROOND_{length}", "AROONU_{length}", "AROONOSC_{length}"],
        regime_type="TREND",
        direction="BIDI",
        lookback=30,
        input_type="hl",  # aroon takes (high, low), not (high, low, close)
    ),
    PtaIndicator(
        id="DPO",
        name="Detrended Price Oscillator",
        category="crossover",
        pandas_ta_func="dpo",
        params={"length": [14, 20]},
        output_columns=["DPO_{length}"],
        regime_type="TREND",
        direction="BIDI",
        lookback=30,
        input_type="close",
    ),
    # =========================================================================
    # NEW TREND INDICATORS (Expanded exploration)
    # =========================================================================
    PtaIndicator(
        id="CHOP",
        name="Choppiness Index",
        category="crossover",
        pandas_ta_func="chop",
        params={"length": [14, 21, 28]},
        output_columns=["CHOP_{length}"],
        regime_type="TREND",
        direction="BIDI",
        lookback=35,
        input_type="hlc",
    ),
    PtaIndicator(
        id="CKSP",
        name="Chande Kroll Stop",
        category="crossover",
        pandas_ta_func="cksp",
        params={"p": [10, 14], "x": [1, 2], "q": [9, 14]},
        output_columns=["CKSPl_{p}_{x}_{q}", "CKSPs_{p}_{x}_{q}"],
        regime_type="TREND",
        direction="BIDI",
        lookback=30,
        input_type="hlc",
    ),
    PtaIndicator(
        id="DECAY",
        name="Linear Decay",
        category="crossover",
        pandas_ta_func="decay",
        params={"length": [5, 10, 14]},
        output_columns=["LDECAY_{length}"],
        regime_type="TREND",
        direction="BIDI",
        lookback=20,
        input_type="close",
    ),
    PtaIndicator(
        id="DECREASING",
        name="Decreasing",
        category="crossover",
        pandas_ta_func="decreasing",
        params={"length": [5, 10, 14]},
        output_columns=["DEC_{length}"],
        regime_type="TREND",
        direction="SHORT",
        lookback=20,
        input_type="close",
    ),
    PtaIndicator(
        id="INCREASING",
        name="Increasing",
        category="crossover",
        pandas_ta_func="increasing",
        params={"length": [5, 10, 14]},
        output_columns=["INC_{length}"],
        regime_type="TREND",
        direction="LONG",
        lookback=20,
        input_type="close",
    ),
    PtaIndicator(
        id="LONG_RUN",
        name="Long Run",
        category="crossover",
        pandas_ta_func="long_run",
        params={"length": [14, 21]},
        output_columns=["LR_{length}"],
        regime_type="TREND",
        direction="LONG",
        lookback=30,
        input_type="close",
    ),
    PtaIndicator(
        id="SHORT_RUN",
        name="Short Run",
        category="crossover",
        pandas_ta_func="short_run",
        params={"length": [14, 21]},
        output_columns=["SR_{length}"],
        regime_type="TREND",
        direction="SHORT",
        lookback=30,
        input_type="close",
    ),
    PtaIndicator(
        id="QSTICK",
        name="Q Stick",
        category="crossover",
        pandas_ta_func="qstick",
        params={"length": [10, 14, 21]},
        output_columns=["QS_{length}"],
        regime_type="TREND",
        direction="BIDI",
        lookback=30,
        input_type="ohlc",
    ),
    PtaIndicator(
        id="VORTEX",
        name="Vortex Indicator",
        category="crossover",
        pandas_ta_func="vortex",
        params={"length": [14, 21, 28]},
        output_columns=["VTXP_{length}", "VTXM_{length}"],
        regime_type="TREND",
        direction="BIDI",
        lookback=35,
        input_type="hlc",
    ),
    PtaIndicator(
        id="VHF",
        name="Vertical Horizontal Filter",
        category="crossover",
        pandas_ta_func="vhf",
        params={"length": [14, 21, 28]},
        output_columns=["VHF_{length}"],
        regime_type="TREND",
        direction="BIDI",
        lookback=35,
        input_type="close",
    ),
]


# =============================================================================
# VOLATILITY INDICATORS (Both regimes)
# =============================================================================

VOLATILITY_INDICATORS = [
    PtaIndicator(
        id="BBANDS",
        name="Bollinger Bands",
        category="volatility",
        pandas_ta_func="bbands",
        params={"length": [10, 20], "std": [1.5, 2.0, 2.5]},
        output_columns=["BBL_{length}_{std}", "BBM_{length}_{std}", "BBU_{length}_{std}", "BBB_{length}_{std}", "BBP_{length}_{std}"],
        regime_type="BOTH",
        direction="BIDI",
        lookback=30,
        input_type="close",
    ),
    PtaIndicator(
        id="ATR",
        name="Average True Range",
        category="volatility",
        pandas_ta_func="atr",
        params={"length": [7, 14, 21]},
        output_columns=["ATRr_{length}"],
        regime_type="BOTH",
        direction="BIDI",
        lookback=30,
        input_type="hlc",
    ),
    PtaIndicator(
        id="NATR",
        name="Normalized ATR",
        category="volatility",
        pandas_ta_func="natr",
        params={"length": [14, 21]},
        output_columns=["NATR_{length}"],
        regime_type="BOTH",
        direction="BIDI",
        lookback=30,
        input_type="hlc",
    ),
    PtaIndicator(
        id="KC",
        name="Keltner Channels",
        category="volatility",
        pandas_ta_func="kc",
        params={"length": [14, 20, 28], "scalar": [1.0, 1.5, 2.0, 2.5]},
        output_columns=["KCLe_{length}_{scalar}", "KCBe_{length}_{scalar}", "KCUe_{length}_{scalar}"],
        regime_type="BOTH",
        direction="BIDI",
        lookback=30,
        input_type="hlc",
    ),
    PtaIndicator(
        id="DONCHIAN",
        name="Donchian Channels",
        category="volatility",
        pandas_ta_func="donchian",
        params={"lower_length": [10, 14, 20, 28], "upper_length": [10, 14, 20, 28]},
        output_columns=["DCL_{lower_length}_{upper_length}", "DCM_{lower_length}_{upper_length}", "DCU_{lower_length}_{upper_length}"],
        regime_type="BOTH",
        direction="BIDI",
        lookback=30,
        input_type="hl",  # donchian takes (high, low), not (high, low, close)
    ),
    PtaIndicator(
        id="MASSI",
        name="Mass Index",
        category="volatility",
        pandas_ta_func="massi",
        params={"fast": [7, 9, 12], "slow": [20, 25, 30]},
        output_columns=["MASSI_{fast}_{slow}"],
        regime_type="BOTH",
        direction="BIDI",
        lookback=40,
        input_type="hl",
    ),
    PtaIndicator(
        id="UI",
        name="Ulcer Index",
        category="volatility",
        pandas_ta_func="ui",
        params={"length": [14, 21]},
        output_columns=["UI_{length}"],
        regime_type="BOTH",
        direction="BIDI",
        lookback=30,
        input_type="close",
    ),
    # =========================================================================
    # NEW VOLATILITY INDICATORS (Expanded exploration)
    # =========================================================================
    PtaIndicator(
        id="ABERRATION",
        name="Aberration",
        category="volatility",
        pandas_ta_func="aberration",
        params={"length": [5, 10, 14]},
        output_columns=["ABER_ZG_{length}", "ABER_SG_{length}", "ABER_XG_{length}", "ABER_ATR_{length}"],
        regime_type="BOTH",
        direction="BIDI",
        lookback=20,
        input_type="hlc",
    ),
    PtaIndicator(
        id="ACCBANDS",
        name="Acceleration Bands",
        category="volatility",
        pandas_ta_func="accbands",
        params={"length": [14, 20, 28]},
        output_columns=["ACCBL_{length}", "ACCBM_{length}", "ACCBU_{length}"],
        regime_type="BOTH",
        direction="BIDI",
        lookback=35,
        input_type="hlc",
    ),
    PtaIndicator(
        id="ATRTS",
        name="ATR Trailing Stop",
        category="volatility",
        pandas_ta_func="atrts",
        params={"length": [14, 21], "multiplier": [2.0, 3.0, 4.0]},
        output_columns=["ATRTSl_{length}_{multiplier}", "ATRTSs_{length}_{multiplier}"],
        regime_type="BOTH",
        direction="BIDI",
        lookback=30,
        input_type="hlc",
    ),
    PtaIndicator(
        id="HWC",
        name="Holt-Winter Channel",
        category="volatility",
        pandas_ta_func="hwc",
        params={"na": [0.2], "nb": [0.1], "nc": [0.1]},
        output_columns=["HWM", "HWU", "HWL"],
        regime_type="BOTH",
        direction="BIDI",
        lookback=30,
        input_type="close",
    ),
    PtaIndicator(
        id="PDIST",
        name="Price Distance",
        category="volatility",
        pandas_ta_func="pdist",
        params={},
        output_columns=["PDIST"],
        regime_type="BOTH",
        direction="BIDI",
        lookback=10,
        input_type="ohlc",
    ),
    PtaIndicator(
        id="RVI",
        name="Relative Volatility Index",
        category="volatility",
        pandas_ta_func="rvi",
        params={"length": [14, 21, 28]},
        output_columns=["RVI_{length}"],
        regime_type="BOTH",
        direction="BIDI",
        lookback=35,
        input_type="hlc",
    ),
    PtaIndicator(
        id="THERMO",
        name="Elder Thermometer",
        category="volatility",
        pandas_ta_func="thermo",
        params={"length": [20, 28]},
        output_columns=["THERMO_{length}", "THERMOma_{length}"],
        regime_type="BOTH",
        direction="BIDI",
        lookback=35,
        input_type="hlc",
    ),
    PtaIndicator(
        id="TRUE_RANGE",
        name="True Range",
        category="volatility",
        pandas_ta_func="true_range",
        params={},
        output_columns=["TRUERANGE"],
        regime_type="BOTH",
        direction="BIDI",
        lookback=10,
        input_type="hlc",
    ),
]


# =============================================================================
# VOLUME INDICATORS (Both regimes)
# =============================================================================

VOLUME_INDICATORS = [
    PtaIndicator(
        id="OBV",
        name="On Balance Volume",
        category="volume",
        pandas_ta_func="obv",
        params={},
        output_columns=["OBV"],
        regime_type="BOTH",
        direction="BIDI",
        lookback=20,
        input_type="cv",
    ),
    PtaIndicator(
        id="AD",
        name="Accumulation/Distribution",
        category="volume",
        pandas_ta_func="ad",
        params={},
        output_columns=["AD"],
        regime_type="BOTH",
        direction="BIDI",
        lookback=20,
        input_type="hlcv",
    ),
    PtaIndicator(
        id="ADOSC",
        name="AD Oscillator",
        category="volume",
        pandas_ta_func="adosc",
        params={"fast": [2, 3, 5], "slow": [8, 10, 14]},
        output_columns=["ADOSC_{fast}_{slow}"],
        regime_type="BOTH",
        direction="BIDI",
        lookback=20,
        input_type="hlcv",
    ),
    PtaIndicator(
        id="CMF",
        name="Chaikin Money Flow",
        category="volume",
        pandas_ta_func="cmf",
        params={"length": [20, 21]},
        output_columns=["CMF_{length}"],
        regime_type="BOTH",
        direction="BIDI",
        lookback=30,
        input_type="hlcv",
    ),
    PtaIndicator(
        id="EFI",
        name="Elder Force Index",
        category="volume",
        pandas_ta_func="efi",
        params={"length": [13, 21]},
        output_columns=["EFI_{length}"],
        regime_type="BOTH",
        direction="BIDI",
        lookback=30,
        input_type="cv",
    ),
    PtaIndicator(
        id="NVI",
        name="Negative Volume Index",
        category="volume",
        pandas_ta_func="nvi",
        params={"length": [1]},
        output_columns=["NVI_{length}"],
        regime_type="BOTH",
        direction="BIDI",
        lookback=30,
        input_type="cv",
    ),
    PtaIndicator(
        id="PVI",
        name="Positive Volume Index",
        category="volume",
        pandas_ta_func="pvi",
        params={"length": [1]},
        output_columns=["PVI_{length}"],
        regime_type="BOTH",
        direction="BIDI",
        lookback=30,
        input_type="cv",
    ),
    PtaIndicator(
        id="VWAP",
        name="VWAP",
        category="volume",
        pandas_ta_func="vwap",
        params={},
        output_columns=["VWAP_D"],
        regime_type="BOTH",
        direction="BIDI",
        lookback=20,
        input_type="hlcv",
    ),
    # =========================================================================
    # NEW VOLUME INDICATORS (Expanded exploration)
    # =========================================================================
    PtaIndicator(
        id="AOBV",
        name="Archer OBV",
        category="volume",
        pandas_ta_func="aobv",
        params={"fast": [4, 8], "slow": [12, 16]},
        output_columns=["OBV", "OBV_min_{fast}", "OBV_max_{slow}"],
        regime_type="BOTH",
        direction="BIDI",
        lookback=25,
        input_type="cv",
    ),
    PtaIndicator(
        id="EOM",
        name="Ease of Movement",
        category="volume",
        pandas_ta_func="eom",
        params={"length": [14, 21]},
        output_columns=["EOM_{length}"],
        regime_type="BOTH",
        direction="BIDI",
        lookback=30,
        input_type="hlcv",
    ),
    PtaIndicator(
        id="KVO",
        name="Klinger Volume Oscillator",
        category="volume",
        pandas_ta_func="kvo",
        params={"fast": [34, 40], "slow": [55, 60]},
        output_columns=["KVO_{fast}_{slow}", "KVOs_{fast}_{slow}"],
        regime_type="BOTH",
        direction="BIDI",
        lookback=70,
        input_type="hlcv",
    ),
    PtaIndicator(
        id="MFI_VOL",
        name="Money Flow Index (Volume-based)",
        category="volume",
        pandas_ta_func="mfi",
        params={"length": [14, 21, 28]},
        output_columns=["MFI_{length}"],
        regime_type="BOTH",
        direction="BIDI",
        lookback=35,
        input_type="hlcv",
    ),
    PtaIndicator(
        id="PVO",
        name="Percentage Volume Oscillator",
        category="volume",
        pandas_ta_func="pvo",
        params={"fast": [12, 14], "slow": [26, 28]},
        output_columns=["PVO_{fast}_{slow}", "PVOh_{fast}_{slow}", "PVOs_{fast}_{slow}"],
        regime_type="BOTH",
        direction="BIDI",
        lookback=40,
        input_type="volume",
    ),
    PtaIndicator(
        id="PVR",
        name="Price Volume Rank",
        category="volume",
        pandas_ta_func="pvr",
        params={},
        output_columns=["PVR"],
        regime_type="BOTH",
        direction="BIDI",
        lookback=10,
        input_type="cv",
    ),
    PtaIndicator(
        id="PVT",
        name="Price Volume Trend",
        category="volume",
        pandas_ta_func="pvt",
        params={},
        output_columns=["PVT"],
        regime_type="BOTH",
        direction="BIDI",
        lookback=20,
        input_type="cv",
    ),
    PtaIndicator(
        id="VWMA",
        name="Volume Weighted MA",
        category="volume",
        pandas_ta_func="vwma",
        params={"length": [10, 14, 20, 30]},
        output_columns=["VWMA_{length}"],
        regime_type="BOTH",
        direction="BIDI",
        lookback=40,
        input_type="cv",
    ),
]


# =============================================================================
# STATISTICS INDICATORS
# =============================================================================

STATISTICS_INDICATORS = [
    PtaIndicator(
        id="ENTROPY",
        name="Entropy",
        category="statistics",
        pandas_ta_func="entropy",
        params={"length": [10, 14, 20]},
        output_columns=["ENTP_{length}"],
        regime_type="BOTH",
        direction="BIDI",
        lookback=25,
        input_type="close",
    ),
    PtaIndicator(
        id="KURTOSIS",
        name="Kurtosis",
        category="statistics",
        pandas_ta_func="kurtosis",
        params={"length": [14, 20, 30]},
        output_columns=["KURT_{length}"],
        regime_type="BOTH",
        direction="BIDI",
        lookback=35,
        input_type="close",
    ),
    PtaIndicator(
        id="MAD",
        name="Mean Absolute Deviation",
        category="statistics",
        pandas_ta_func="mad",
        params={"length": [14, 20, 30]},
        output_columns=["MAD_{length}"],
        regime_type="BOTH",
        direction="BIDI",
        lookback=35,
        input_type="close",
    ),
    PtaIndicator(
        id="MEDIAN",
        name="Median",
        category="statistics",
        pandas_ta_func="median",
        params={"length": [14, 20, 30]},
        output_columns=["MEDIAN_{length}"],
        regime_type="BOTH",
        direction="BIDI",
        lookback=35,
        input_type="close",
    ),
    PtaIndicator(
        id="QUANTILE",
        name="Quantile",
        category="statistics",
        pandas_ta_func="quantile",
        params={"length": [20, 30], "q": [0.25, 0.5, 0.75]},
        output_columns=["QTL_{length}_{q}"],
        regime_type="BOTH",
        direction="BIDI",
        lookback=35,
        input_type="close",
    ),
    PtaIndicator(
        id="SKEW",
        name="Skewness",
        category="statistics",
        pandas_ta_func="skew",
        params={"length": [14, 20, 30]},
        output_columns=["SKEW_{length}"],
        regime_type="BOTH",
        direction="BIDI",
        lookback=35,
        input_type="close",
    ),
    PtaIndicator(
        id="STDEV",
        name="Standard Deviation",
        category="statistics",
        pandas_ta_func="stdev",
        params={"length": [14, 20, 30]},
        output_columns=["STDEV_{length}"],
        regime_type="BOTH",
        direction="BIDI",
        lookback=35,
        input_type="close",
    ),
    PtaIndicator(
        id="VARIANCE",
        name="Variance",
        category="statistics",
        pandas_ta_func="variance",
        params={"length": [14, 20, 30]},
        output_columns=["VAR_{length}"],
        regime_type="BOTH",
        direction="BIDI",
        lookback=35,
        input_type="close",
    ),
    PtaIndicator(
        id="ZSCORE",
        name="Z-Score",
        category="statistics",
        pandas_ta_func="zscore",
        params={"length": [14, 20, 30]},
        output_columns=["ZS_{length}"],
        regime_type="REVERSAL",
        direction="BIDI",
        lookback=35,
        input_type="close",
    ),
]


# =============================================================================
# CYCLE INDICATORS
# =============================================================================

CYCLE_INDICATORS = [
    PtaIndicator(
        id="EBSW",
        name="Even Better Sinewave",
        category="cycle",
        pandas_ta_func="ebsw",
        params={"length": [20, 30, 40]},
        output_columns=["EBSW_{length}"],
        regime_type="REVERSAL",
        direction="BIDI",
        lookback=50,
        input_type="close",
    ),
]


# =============================================================================
# CANDLE PATTERN INDICATORS
# Uses cdl_pattern with pattern name - returns 100/-100/0
# =============================================================================

# List of all supported candle patterns
CANDLE_PATTERN_NAMES = [
    "doji",
    "hammer",
    "hangingman",
    "invertedhammer",
    "shootingstar",
    "engulfing",
    "harami",
    "haramicross",
    "morningstar",
    "eveningstar",
    "morningdojistar",
    "eveningdojistar",
    "3whitesoldiers",
    "3blackcrows",
    "3inside",
    "3outside",
    "piercing",
    "darkcloudcover",
    "marubozu",
    "spinningtop",
    "longleggeddoji",
    "dragonflydoji",
    "gravestonedoji",
    "belthold",
    "kicking",
    "matchinglow",
    "takuri",
    "tasukigap",
    "tristar",
]


def _create_candle_indicator(pattern_name: str) -> PtaIndicator:
    """Create a PtaIndicator for a candle pattern."""
    # Determine direction based on typical pattern meaning
    bullish_patterns = [
        "hammer", "invertedhammer", "morningstar", "morningdojistar",
        "3whitesoldiers", "3inside", "piercing", "bullishengulfing",
        "dragonflydoji", "takuri", "matchinglow",
    ]
    bearish_patterns = [
        "hangingman", "shootingstar", "eveningstar", "eveningdojistar",
        "3blackcrows", "darkcloudcover", "gravestonedoji",
    ]

    if pattern_name in bullish_patterns:
        direction = "LONG"
    elif pattern_name in bearish_patterns:
        direction = "SHORT"
    else:
        direction = "BIDI"

    return PtaIndicator(
        id=f"CDL_{pattern_name.upper()}",
        name=f"Candle {pattern_name.title()}",
        category="candle",
        pandas_ta_func="cdl_pattern",
        params={"name": [pattern_name]},
        output_columns=[f"CDL_{pattern_name.upper()}"],
        regime_type="REVERSAL",
        direction=direction,
        lookback=10,
        input_type="ohlc",
    )


# Generate all candle pattern indicators
CANDLE_INDICATORS = [_create_candle_indicator(p) for p in CANDLE_PATTERN_NAMES]


# =============================================================================
# ALL INDICATORS
# =============================================================================

ALL_INDICATORS = (
    MOMENTUM_INDICATORS
    + TREND_INDICATORS
    + CROSSOVER_INDICATORS
    + VOLATILITY_INDICATORS
    + VOLUME_INDICATORS
    + STATISTICS_INDICATORS
    + CYCLE_INDICATORS
    + CANDLE_INDICATORS
)

# Index by ID
INDICATORS_BY_ID = {ind.id: ind for ind in ALL_INDICATORS}

# Index by category
INDICATORS_BY_CATEGORY = {}
for ind in ALL_INDICATORS:
    if ind.category not in INDICATORS_BY_CATEGORY:
        INDICATORS_BY_CATEGORY[ind.category] = []
    INDICATORS_BY_CATEGORY[ind.category].append(ind)

# Index by regime
INDICATORS_BY_REGIME = {"TREND": [], "REVERSAL": [], "BOTH": []}
for ind in ALL_INDICATORS:
    INDICATORS_BY_REGIME[ind.regime_type].append(ind)


def get_indicator(indicator_id: str) -> PtaIndicator:
    """Get indicator by ID."""
    if indicator_id not in INDICATORS_BY_ID:
        raise ValueError(f"Unknown indicator ID: {indicator_id}")
    return INDICATORS_BY_ID[indicator_id]


def get_indicators_by_category(category: str) -> list[PtaIndicator]:
    """Get all indicators in a category."""
    return INDICATORS_BY_CATEGORY.get(category, [])


def get_indicators_by_regime(regime_type: str) -> list[PtaIndicator]:
    """Get indicators suitable for a regime type."""
    if regime_type == "MIXED":
        return ALL_INDICATORS
    # TREND includes TREND + BOTH, REVERSAL includes REVERSAL + BOTH
    both = INDICATORS_BY_REGIME.get("BOTH", [])
    specific = INDICATORS_BY_REGIME.get(regime_type, [])
    return specific + both


def get_indicators_by_direction(direction: str) -> list[PtaIndicator]:
    """Get indicators matching a direction."""
    if direction == "BIDI":
        return ALL_INDICATORS
    return [i for i in ALL_INDICATORS if i.direction == direction or i.direction == "BIDI"]


def get_all_indicator_ids() -> list[str]:
    """Get all indicator IDs."""
    return list(INDICATORS_BY_ID.keys())
